In [1]:


import numpy as np 
import pandas as pd 



import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



/kaggle/input/food-delivery-time-prediction-dataset/Delivery time/deliverytime.txt


In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [3]:
df=pd.read_csv("/kaggle/input/food-delivery-time-prediction-dataset/Delivery time/deliverytime.txt")

**Datas parameter:.......**

In [4]:
print(df.head())

     ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  4607     INDORES13DEL02                   37                      4.9   
1  B379     BANGRES18DEL02                   34                      4.5   
2  5D6D     BANGRES19DEL01                   23                      4.4   
3  7A6A    COIMBRES13DEL02                   38                      4.7   
4  70A2     CHENRES12DEL01                   32                      4.6   

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            22.745049             75.892471                   22.765049   
1            12.913041             77.683237                   13.043041   
2            12.914264             77.678400                   12.924264   
3            11.003669             76.976494                   11.053669   
4            12.972793             80.249982                   13.012793   

   Delivery_location_longitude Type_of_order Type_of_vehicle  Time_taken(min)  
0     

****Itchecks for missing values (null or NaN) in a DataFrame and returns the count of null values in each column.****

In [5]:
max_row = df.loc[df['Delivery_person_Ratings'].idxmax()]
print("Delivery Person with Highest Rating:")
print(max_row)

Delivery Person with Highest Rating:
ID                                           46D
Delivery_person_ID                BANGRES05DEL01
Delivery_person_Age                           50
Delivery_person_Ratings                      6.0
Restaurant_latitude                   -12.970324
Restaurant_longitude                  -77.645748
Delivery_location_latitude             13.010324
Delivery_location_longitude            77.685748
Type_of_order                              Meal 
Type_of_vehicle                electric_scooter 
Time_taken(min)                               25
Name: 3586, dtype: object


In [6]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Type_of_order                  0
Type_of_vehicle                0
Time_taken(min)                0
dtype: int64

In [7]:
R = 6371.0

In [8]:
def deg_to_rad(degrees):
    return degrees*(np.pi/180)

In [9]:
import numpy as np

def spherical_cosine_distance(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    return R * np.arccos(
        np.sin(lat1) * np.sin(lat2) +
        np.cos(lat1) * np.cos(lat2) * np.cos(lon2 - lon1)
    )


In [10]:
df['distance'] = df.apply(
    lambda row: spherical_cosine_distance(
        row['Restaurant_latitude'],
        row['Restaurant_longitude'],
        row['Delivery_location_latitude'],
        row['Delivery_location_longitude']
    ), axis=1
)


In [11]:
print(df[['Restaurant_latitude', 'Restaurant_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude', 'distance']].head())
print(df.head())

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            22.745049             75.892471                   22.765049   
1            12.913041             77.683237                   13.043041   
2            12.914264             77.678400                   12.924264   
3            11.003669             76.976494                   11.053669   
4            12.972793             80.249982                   13.012793   

   Delivery_location_longitude   distance  
0                    75.912471   3.025149  
1                    77.813237  20.183530  
2                    77.688400   1.552758  
3                    77.026494   7.790401  
4                    80.289982   6.210138  
     ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  4607     INDORES13DEL02                   37                      4.9   
1  B379     BANGRES18DEL02                   34                      4.5   
2  5D6D     BANGRES19DEL01                   23    

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


2025-07-12 13:26:24.845733: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1752326785.194442      35 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1752326785.291259      35 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [45]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import joblib

# Your feature selection
features = [
    'Delivery_person_Age', 'Delivery_person_Ratings', 'distance',
    'Type_of_order', 'Type_of_vehicle'
]

target = 'Time_taken(min)'

In [46]:
df[features]

,Delivery_person_Age,Delivery_person_Ratings,distance,Type_of_order,Type_of_vehicle
0,37,4.9,3.025149,Snack,motorcycle
1,34,4.5,20.183530,Snack,scooter
2,23,4.4,1.552758,Drinks,motorcycle
3,38,4.7,7.790401,Buffet,motorcycle
4,32,4.6,6.210138,Snack,scooter
...,...,...,...,...,...
45588,30,4.8,1.489846,Meal,motorcycle
45589,21,4.6,11.007735,Buffet,motorcycle
45590,30,4.9,4.657195,Drinks,scooter
45591,20,4.7,6.232393,Snack,motorcycle


In [64]:
X = df[features]
X

,Delivery_person_Age,Delivery_person_Ratings,distance,Type_of_order,Type_of_vehicle
0,37,4.9,3.025149,Snack,motorcycle
1,34,4.5,20.183530,Snack,scooter
2,23,4.4,1.552758,Drinks,motorcycle
3,38,4.7,7.790401,Buffet,motorcycle
4,32,4.6,6.210138,Snack,scooter
...,...,...,...,...,...
45588,30,4.8,1.489846,Meal,motorcycle
45589,21,4.6,11.007735,Buffet,motorcycle
45590,30,4.9,4.657195,Drinks,scooter
45591,20,4.7,6.232393,Snack,motorcycle


In [66]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
import joblib

# Define columns
numeric_features = ['Delivery_person_Age', 'Delivery_person_Ratings', 'distance']
categorical_features = ['Type_of_order', 'Type_of_vehicle']

# Create column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', MinMaxScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# Combine preprocessing and model
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    # ('model', model)  # If using sklearn model. Skip for Keras
])

# Fit only the preprocessor on X
pipeline.fit(X)

# Save the whole pipeline (only 1 file)
joblib.dump(pipeline, 'preprocessing_pipeline.pkl')


['preprocessing_pipeline.pkl']

In [67]:
X = pipeline.transform(X)

In [70]:
X[2]

array([2.28571429e-01, 6.80000000e-01, 4.45327632e-06, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00])

In [71]:
2.28571429e-01

0.228571429

In [72]:
df[target].values

array([24, 33, 26, ..., 16, 26, 36])

In [73]:
y = df[target].values.reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


target_scaler = MinMaxScaler()
y_train_scaled = target_scaler.fit_transform(y_train)
y_test_scaled = target_scaler.transform(y_test)
joblib.dump(target_scaler, "target_scaler.pkl")

['target_scaler.pkl']

In [ ]:
X_train

In [36]:
# Load required assets
import joblib
import pandas as pd

# Example sample input
sample = pd.DataFrame([{
    'Delivery_person_Age': 37,
    'Delivery_person_Ratings': 4.9,
    'distance': 3.02,
    'Type_of_order': 'Snack',
    'Type_of_vehicle': 'scooter'
}])

pipeline = joblib.load("preprocessing_pipeline.pkl")
target_scaler = joblib.load("target_scaler.pkl")

X_train  = pipeline.transform(sample_encoded)


# 🔥 Now use this for prediction
prediction_scaled = model.predict(sample_scaled)
prediction = target_scaler.inverse_transform(prediction_scaled)[0][0]


/usr/local/lib/python3.11/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


In [37]:
X_train[0]


array([6.28571429e-01, 7.80000000e-01, 7.89845700e-05, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [34]:
max(y)

array([54])

In [59]:
model = Sequential()

# Input layer + 1st hidden layer
model.add(Dense(64, input_dim=X_train.shape[1], activation='softmax'))
model.add(Dropout(0.2))  # optional: prevents overfitting

# 2nd hidden layer
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))

# Output layer for regression
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


In [74]:
history = model.fit(X_train, y_train_scaled, epochs=50, batch_size=32,validation_split=0.2,verbose=1)

Epoch 1/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 40.2538 - mae: 2.4449 - val_loss: 0.0418 - val_mae: 0.1596
Epoch 2/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0477 - mae: 0.1713 - val_loss: 0.0387 - val_mae: 0.1589
Epoch 3/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0414 - mae: 0.1631 - val_loss: 0.0386 - val_mae: 0.1598
Epoch 4/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0405 - mae: 0.1619 - val_loss: 0.0385 - val_mae: 0.1594
Epoch 5/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0401 - mae: 0.1608 - val_loss: 0.0383 - val_mae: 0.1588
Epoch 6/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0398 - mae: 0.1610 - val_loss: 0.0383 - val_mae: 0.1575
Epoch 7/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0393 - mae: 0.1598 - val_loss: 0.0381 - val_mae: 0.1583
Epoch 8/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0392 - mae: 0.1594 - val_loss: 0.0377 - val_mae: 0.1565
Epoch 9/50
912/912 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - l

In [76]:
loss,mae = model.evaluate(X_test, y_test_scaled, verbose=1)
print(f"Test MAE: {mae:.2f} minutes")

285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0622 - mae: 0.2114
Test MAE: 0.21 minutes


In [99]:


# Sample input
sample = pd.DataFrame([{
    'Delivery_person_Age': 30,
    'Delivery_person_Ratings': 4.8,
    'distance': 5.2,
    'Type_of_order': 'Snack',
    'Type_of_vehicle': 'scooter'
}])

sample_scaled = pipeline.transform(sample)
prediction_scaled = model.predict(sample_scaled)
prediction = target_scaler.inverse_transform(prediction_scaled)[0][0]
prediction = round(prediction, 2)
print(f"Predicted Delivery Time: ",prediction," minutes" )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step
Predicted Delivery Time:  35.48  minutes


In [96]:
sample_scaled

array([[4.28571429e-01, 7.60000000e-01, 1.89675123e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
!pip show pandas


In [95]:
model.save("model-final.h5")

In [98]:
from tensorflow.keras.models import load_model
model = load_model("model-final.h5")

In [ ]:
import joblib
joblib.dump(scaler, "feature_scaler2.pkl")


In [ ]:
import joblib
scaler = joblib.load("feature_scaler2.pkl")


In [ ]:
import joblib
joblib.dump(scaler, "target_scalar2.pkl")

In [ ]:
import joblib
scaler = joblib.load("target_scalar2.pkl")

In [ ]:
import pickle
pickle.dump(df_encoded.columns.tolist(), open("columns2.pkl", "wb"))
